# Begin11. Даны два ненулевых числа. Найти сумму, разность, произведение и частное их модулей.
a = float(input())
b = float(input())
sum = abs(a + b)
dif = abs(a - b)
com = abs(a * b)
div = abs(a / b)
print(sum)
print(dif)
print(com)
print(div)